#!/usr/bin/env node
// Converts scripts/generatedStories.json → data/generatedStories.ts
// Run from the StellarTales/ directory: node scripts/buildGeneratedStoriesSeed.js

const fs = require('fs');
const path = require('path');

const INPUT  = path.join(__dirname, 'generatedStories.json');
const OUTPUT = path.join(__dirname, '../data/generatedStories.ts');

const data = JSON.parse(fs.readFileSync(INPUT, 'utf8'));

const objectEntries = Object.entries(data).map(([objectId, cultures]) => {
  const cultureEntries = Object.entries(cultures).map(([culture, story]) => {
    // Escape backticks in body text
    const safeTitle = story.title.replace(/`/g, '\\`').replace(/\${/g, '\\${');
    const safeBody  = story.body.replace(/`/g, '\\`').replace(/\${/g, '\\${');
    return `    ${culture}: {\n      title: \`${safeTitle}\`,\n      body: \`${safeBody}\`,\n    }`;
  });
  return `  ${objectId}: {\n${cultureEntries.join(',\n')},\n  }`;
});

const ts = `// AUTO-GENERATED by scripts/buildGeneratedStoriesSeed.js — do not edit by hand.
// Re-generate by running: node scripts/generateStories.js && node scripts/buildGeneratedStoriesSeed.js
import { CultureKey } from './anchorObjects';
import { SeedStory } from './seedStories';

export const GENERATED_STORIES: Partial<Record<string, Partial<Record<CultureKey, SeedStory>>>> = {
${objectEntries.join(',\n')},
};
`;

fs.writeFileSync(OUTPUT, ts);

const storyCount = Object.values(data).reduce((n, c) => n + Object.keys(c).length, 0);
console.log(`✓ Written ${storyCount} stories to data/generatedStories.ts (${(fs.statSync(OUTPUT).size / 1024).toFixed(0)} KB)`);
